#!/usr/bin/bash

factorize() {
    if [ $# -ne 3 ]; then
        args=("$@")
        counter=0
        second=1
        for i in ${args[*]}; do
            if [ $counter -gt 1 ]; then
                second=$(echo $i*$second | bc)
            fi
            counter=$((counter + 1))
        done
    else
        second=$3
    fi

    first=$2
    number=$(echo "$1" | tr ':' '=')

    result=$(echo "if($second > $first) 1 else 0" | bc)
    if ((result == 1)); then
        temp=$first
        first=$second
        second=$temp
    fi

    echo "$number$first*$second"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <test_file>'
    exit 1
else
    while read i; do

        result=$(factor "$i")
        factorize $result

    done <"$1"
fi
