#!/usr/bin/python3
import sys
import ctypes


def print_factors():
    func = ctypes.CDLL("./lib_factors_functions.so")
    func.trial_division.argtypes = [ctypes.c_long]
    with open(sys.argv[1]) as f:
        line = f.readline()
        while line != '':
            num = int(line)
            func.trial_division(num)
            line = f.readline()


if __name__ == "__main__":
    print_factors()
